spring:
  # config:
  #   activate:
  #     on-profile: application-jdbc
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/swtodo?autoReconnect=true&&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: kimsw
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

      
server:
  port: 8090
  servlet:
    encoding:
      force: false
      charset: UTF-8

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /logs/abc.log
    max-history: 30
  level:
    org:
      springframework: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"


