spring:
  profiles:
    include:
    - jdbc
      
server:
  port: 8090
  servlet:
    encoding:
      force: false
      charset: UTF-8

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /logs/abc.log
    max-history: 30
  level:
    org:
      springframework: INFO
  logback:
    rollingpolicy:
      file-name-pattern: "/logs/abc.%d{yyyy-MM-dd}.%i"
